package com.dbnav.driver;

import com.dbnav.config.ConfigJsonMapper;
import com.dbnav.config.DbNavProperties;
import com.dbnav.driver.model.DriverSeedEntry;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.Resource;
import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.InputStream;
import java.util.List;
import java.util.Map;

/**
 * Loads driver seed metadata from JSON into the registry on startup.
 *
 * Aligned with RaccoonX's seed_driver_registry():
 *   - Only runs if the registry table is empty (first run)
 *   - seed JSON contains metadata without jar_path (resolved at import)
 *   - After seed import, calls scan_driver_dirs to verify JARs exist on disk
 *
 * The seed file is the equivalent of RaccoonX's modules/config/drivers_seed.json,
 * generated by export_drivers_seed() and NOT committed to git (but we include it
 * for convenience — it's metadata only, no JARs).
 */
@Slf4j
@Component
public class DriverSeedLoader {

    private final DriverRegistry registry;
    private final DriverPathResolver pathResolver;
    private final DbTypeRegistry dbTypeRegistry;
    private final DbNavProperties properties;
    private final ObjectMapper objectMapper = ConfigJsonMapper.get();

    public DriverSeedLoader(DriverRegistry registry,
                             DriverPathResolver pathResolver,
                             DbTypeRegistry dbTypeRegistry,
                             DbNavProperties properties) {
        this.registry = registry;
        this.pathResolver = pathResolver;
        this.dbTypeRegistry = dbTypeRegistry;
        this.properties = properties;
    }

    /**
     * Load seed drivers if registry is empty. Called on application startup.
     *
     * Aligned with RaccoonX's seed_driver_registry():
     *   1. Check if table is empty
     *   2. Parse JSON seed file
     *   3. For each entry, resolve jar_path from disk (drivers/<db_type>/<version>/<jar>)
     *   4. INSERT with resolved path
     *   5. ensureActivation()
     */
    public void loadSeedIfEmpty() {
        if (!registry.isEmpty()) {
            log.info("Driver registry already populated, skipping seed load");
            return;
        }

        log.info("Driver registry is empty, loading seed from {}", properties.getDriversSeed());

        try {
            DefaultResourceLoader loader = new DefaultResourceLoader();
            Resource resource = loader.getResource(properties.getDriversSeed());

            List<DriverSeedEntry> seeds;
            try (InputStream is = resource.getInputStream()) {
                // Parse the outer JSON object, extract "drivers" array
                Map<String, Object> root = objectMapper.readValue(is,
                        new TypeReference<Map<String, Object>>() {});
                Object driversObj = root.get("drivers");
                seeds = objectMapper.convertValue(driversObj,
                        new TypeReference<List<DriverSeedEntry>>() {});
            }

            if (seeds == null || seeds.isEmpty()) {
                log.warn("Seed file contains no drivers");
                return;
            }

            int loaded = 0;
            for (DriverSeedEntry seed : seeds) {
                // Resolve jar_path from disk
                File jarFile = pathResolver.resolveJarPath(
                        seed.getDbType(), seed.getVersion(), seed.getJarFilename());

                String jarPath;
                long fileSize = seed.getFileSize() != null ? seed.getFileSize() : 0;

                if (jarFile != null && jarFile.exists()) {
                    jarPath = jarFile.getAbsolutePath();
                    fileSize = jarFile.length();
                    loaded++;
                } else {
                    // JAR not on disk yet — register metadata only
                    // Path will be resolved on demand at connection time
                    jarPath = pathResolver.getDriversDir().getAbsolutePath() + File.separator +
                            seed.getDbType() + File.separator + seed.getVersion() +
                            File.separator + seed.getJarFilename();
                    log.warn("Seed JAR not found on disk: {} v{} {} (metadata registered, place JAR at {})",
                            seed.getDbType(), seed.getVersion(), seed.getJarFilename(), jarPath);
                }

                boolean isActive = seed.getIsActive() != null && seed.getIsActive() == 1;
                String driverClass = seed.getDriverClass() != null ? seed.getDriverClass() :
                        dbTypeRegistry.getDriverClassHint(seed.getDbType());

                registry.insertRaw(
                        seed.getDbType(),
                        seed.getVersion(),
                        driverClass,
                        seed.getJarFilename(),
                        jarPath,
                        fileSize,
                        isActive,
                        seed.getNote()
                );
            }

            // Ensure at least one active per type
            registry.ensureActivation();

            log.info("Seed loading complete: {} drivers from seed ({} JARs found on disk)",
                    seeds.size(), loaded);

        } catch (Exception e) {
            log.error("Failed to load driver seed", e);
        }
    }
}
